---
- name: Install packages
  become: yes
  package:
    name: "{{ packages | default([]) }}"
    state: present

- name: Start & enable libvirtd
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Make sure user in libvirt groups
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: "{{ kvmhost_groups | default([], true) }}"
    append: yes

- name: Configure storage pools
  include_role:
    name: stackhpc.libvirt-host
    tasks_from: pools.yml

- name: Set SELinux types for dir storage pools
  become: yes
  sefcontext:
    target: "{{ pool.path }}(/.*)?"
    setype: virt_image_t
    state: present
  loop: "{{ libvirt_host_pools | selectattr('type', 'eq', 'dir') | list}}"
  loop_control:
    loop_var: pool
    label: "{{ pool.path }}"

- name: Update SELinux file contexts
  become: yes
  command: restorecon -irv "{{pool.path}}"
  loop: "{{ libvirt_host_pools | selectattr('type', 'eq', 'dir') | list }}"
  loop_control:
    loop_var: pool
    label: "{{ pool.path }}"
