---
- name: check input hardware
  command: lshw -short -c input
  become: yes
  register: input_hardware
  changed_when: false

- when: input_hardware.stdout | lower is search("razer")
  include_role:
    name: openrazer

- when: input_hardware.stdout | lower is search("corsair")
  include_role:
    name: ckb_next
