---
- include_tasks: packages.yml
- include_tasks: hardware.yml
- include_tasks: laptop.yml
  when: ansible_form_factor == "Laptop"
- include_role:
    name: giovtorres.tuned
    apply:
      become: yes
