---
- name: Install packages
  become: yes
  package:
    name: "{{ packages }}"
    state: present
  tags: dnf

- name: Add flatpak remotes
  flatpak_remote:
    name: flathub
    method: user
    state: present
    flatpakrepo_url: "{{ item }}"
  loop: "{{ flatpak_remotes }}"
  tags: flatpak

- name: Install flatpaks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpaks }}"
  tags: flatpak
